name = "shopleaftix" # Mantenha o nome do seu projeto
workers_dev = true
compatibility_date = "2024-01-01"

[assets]
directory = "./dist"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true
